### ISSUE TITLE
Is error handling inside pipeline possible?

### ISSUE THREAD

**Issue by spivachek** [tomerfiliba/plumbum#145]
In a pipeline we get exit code only from the last command. How can we know if one of the previous commands failed? Here is the code to show the problem:

``` python
from plumbum.cmd import yes, head

# 'head' gets incorrect argument, exit code = 1, ok
chain = yes | head["-x"]
print chain
print chain.run(retcode=None)

# 'yes' gets incorrect argument, exit code = 0 as if it's ok, bad
chain = yes["-x"] | head
print chain
print chain.run(retcode=None)
```

From the output we see that there is no trace of error in the second pipeline:

```
/usr/bin/yes | /usr/bin/head -x
(1, u'', u"head: unknown option -- x\nTry `/usr/bin/head --help' for more information.\n")
/usr/bin/yes -x | /usr/bin/head
(0, u'', u'')
```

Can we have something like 'pipefail' option or 'PIPESTATUS' array in Bash?

**Comment by leoncamel** [comment]
Please release a new version 1.4.3. The latest version at pypi is 1.4.2.
