### ISSUE TITLE
Strange remote environment variable causes error

### ISSUE THREAD

**Issue by pigay** [tomerfiliba/plumbum#162]
Hi,

with a SshMachine, strange remote environment variable causes an error:

```
Traceback (most recent call last):
  File "rpyc_test.py", line 5, in <module>
    mach = SshMachine("avakas.mcia.univ-bordeaux.fr", user="pigay", keyfile="/home/pigay/.ssh/id_rsa")
  File "/usr/local/lib/python2.7/dist-packages/plumbum/machines/ssh_machine.py", line 106, in __init__
    new_session = new_session)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/machines/remote.py", line 132, in __init__
    self.env = RemoteEnv(self)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/machines/remote.py", line 18, in __init__
    self._curr = dict(line.split("=", 1) for line in self.remote._session.run("env")[1].splitlines())
ValueError: dictionary update sequence element #44 has length 1; 2 is required
```

The environment that causes this error is the second part of a function definition. Here is what appears with an `env` command on the remote machine:
```
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
```

The return character in BASH_FUNC_module causes an error in `machines/remote.py` because of splitline call, I think.

Would it be ok to simply catch the ValuerError, or to use a more complicated parsing method?

Regards,

Pierre

**Comment by campbellr** [comment]
I've also been hitting this.

I have the following environment variable that breaks due to `splitlines`: `'COMP_WORDBREAKS= \t\n"\'><;|&(:'`

This seems to fix it:

```
- self._curr = dict(line.split("=", 1) for line in self.remote._session.run("env")[1].splitlines())
+ self._curr = dict(line.split("=", 1) for line in self.remote._session.run("env -0")[1].split('\x00'))
```

Although I'm not sure how cross-platform the `-0` flag is for `env`...

**Comment by campbellr** [comment]
Awesome, thanks @tomerfiliba (sorry about the broken 'fix' i suggested)!

**Comment by pigay** [comment]
Thanks @tomerfiliba ;)
