### ISSUE TITLE
Create context manager for virtualenv

### ISSUE THREAD

**Issue by gotgenes** [tomerfiliba/plumbum#168]
Hi,

I'm starting to use plumbum and am enjoying the library so far. I have the need to execute several commands in the context of an activated virtualenv. I'm looking for an API similar to [fabric-virtualenv](https://pypi.python.org/pypi/fabric-virtualenv/); specifically:

``` python
>>> from fabvenv import virtualenv
>>> with virtualenv('/home/me/venv/'):
...     run('python foo')
```

I couldn't find any documentation on creating a new context manager for plumbum, although it's clear plumbum ships with some of its own context managers, e.g.,

``` python
>>> with local.env(FOO="BAR"):
...     local.python("-c", "import os;print os.environ['FOO']")
...     with local.env(FOO="SPAM"):
...         local.python("-c", "import os;print os.environ['FOO']")
...     local.python("-c", "import os;print os.environ['FOO']")
...
'BAR\r\n'
'SPAM\r\n'
'BAR\r\n'
```

Can you please point me in the right direction for creating a virtualenv context manager?

**Comment by gotgenes** [comment]
Thanks @tomerfiliba. After looking at [the virtualenv documentation for the activate script](https://virtualenv.readthedocs.org/en/latest/userguide.html#activate-script), it seems the only necessary alteration was inserting the virtualenv's `bin/` directory as the first entry of the `PATH` environmental variable. I arrived at the following

```python
@contextmanager
def virtualenv(virtualenv_dir):
    """A context manager for executing commands within the context of a
    Python virtualenv.

    >>> with virtualenv('/path/to/virtualenv'):
    ...     print(local.python("-c", "import sys;
                               print(sys.executable)"))
    ... #...

    """
    old_path = local.env['PATH']
    virtualenv_bin_dir = (Path(virtualenv_dir) / 'bin').resolve()
    new_path = '{}:{}'.format(str(virtualenv_bin_dir), old_path)
    local.env['PATH'] = new_path
    old_python = local.python
    new_python = local['python']
    local.python = new_python
    try:
        yield
    finally:
        local.env['PATH'] = old_path
        local.python = old_python
```

It seems to work suitably.

One concern I have is that this is probably not parallel-safe. That is, this change is global and affects all operations using the `local` object. This becomes a concern to me when I use plumbum in the context of [doit](http://pydoit.org/), which can execute tasks in parallel. If one task uses this context manager, it will change the `PATH` environmental variable and the `python` executable for all currently executing tasks. @tomerfiliba, do you have any suggestions on creating a version of this context manager that is parallel-safe (i.e., does not change global state)?

**Comment by lastorset** [comment]
Stranger here (never tried plumbum but interested in programmatic access to virtualenvs), but it seems it would be threadsafe if you keep a modified environment as a local variable and pass it to `Popen` (or `run`) as the `env` argument, without touching the process-global environment. With no teardown (other than the ordinary)) it no longer makes sense as a context manager.

```python
def virtualenv_runner(venv_dir):
    virtualenv_path = '{}:{}'.format(venv_dir, os.environ['PATH'])
    virtual_environ = dict(os.environ)
    virtual_environ['PATH'] = virtualenv_path
    if 'PYTHONHOME' in virtual_environ:
        del virtual_environ['PYTHONHOME']

    virtualenv_python = os.path.join(venv_dir, 'bin', 'python')

    def _virtualenv_run(args, **kwargs):
        if args[0] == 'python':
            args[0] = virtualenv_python
        run(args, env=virtual_environ, **kwargs)

    return _virtualenv_run


myvirtualenv_run = virtualenv_runner('/path/to/virtualenv')
myvirtualenv_run(['python', '-c', 'import sys; print(sys.executable)'])
```
