### ISSUE TITLE
TEE doesn't seem to work on Windows

### ISSUE THREAD

**Issue by ylangisc** [tomerfiliba/plumbum#170]
Using the TEE modifier on Windows gives the following error:

```
  File "D:\apps\Python34\lib\site-packages\plumbum\commands\modifiers.py", line 160, in __rand__
    ready, _, _ = select((out, err), (), ())
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

Plumbum version 1.4.2
Python 3.4.2

**Comment by tomerfiliba** [comment]
Well it's the other way around, it's pipes that don't work on Windows. In
other words, select can't work with anything that's not sockets. Not
something we can fix in plumbum. The alternative is to spawn a thread for
each pipe. You're welcome to submit a patch.
