### ISSUE TITLE
remote tempdir only works on Linux-like systems

### ISSUE THREAD

**Issue by abarnert** [tomerfiliba/plumbum#175]
`BaseRemoteMachine.tempdir` runs `mktemp -d`, with no other parameters.

With the Todd Miller or GNU coreutils versions of `mktemp`, this works fine (at least under GNU, it uses a template of `tmp.XXXXXXXXXX`).

But with most other implementations, it's an error. The traditional command (it's not actually standardized, but was added in OpenBSD and FreeBSD and copied from there to many other systems) requires a template parameter. Most current *BSD versions allow a prefix instead of a template, but you still have to specify one or the other.

This means that if you try to use `tempdir` on a `RemoteMachine` that's connected to, say, OS X, or FreeBSD, you get a `ProcessExecutionError`.

This also means that RPyC ZeroDeploy doesn't work on OS X, FreeBSD, etc. targets.

Changing the command to explicitly use `tmp.XXXXXXXXXX` will make it work _almost_ everywhere, and work exactly the same as it has on almost every linux distro (and on Cygwin), which I think is the best option.

**Comment by tomerfiliba** [comment]
A pull request would be welcomed :)

-tomer

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>

**Comment by tomerfiliba** [comment]
Oh, that was quick :)

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>
