### ISSUE TITLE
Recursive searching returns empty list

### ISSUE THREAD

**Issue by bfo** [tomerfiliba/plumbum#181]
plumbum 1.4.2, python 3.4.

My goal is to get paths of all C files under current directory with unlimited depth. _p_ is a LocalPath object. When I get the actual value of p and issue in system console
```bash
find ~/value/of/p -iname '*.c'
```
I get a list of files. However, doing any of the following returns:
```python
p // "*/*.c" => []
p // "*.c" => []
(find[p]['-iname']["'*.c"])() => ''
```
What's more, printing `find[p]['-iname']["'*.c"]` gives the correct command. What am I doing wrong?

**Comment by bfo** [comment]
Ok, I figured it out: single `*/*` sequence equals one level down the hierarchy, so `p // '*/*.c` returns some results. And with find command, there is no need to put '' around `*.c`.

**Comment by tomerfiliba** [comment]
btw, you can also use path.walk, which recursively walks a subdir. if
accepts filters which you can use to select only "*.c"

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>

**Comment by AllanLRH** [comment]
`os.path.walk` can be a little annoying and un-pythonic. Check out the path.py module.
