### ISSUE TITLE
Fallback using getattr with pb.cmd

### ISSUE THREAD

**Issue by mbarkhau** [tomerfiliba/plumbum#193]
Checking if a command is available using `hasattr` seems to work.

    gzip_cmd = pb.cmd.pigz if hasattr(pb.cmd, 'pigz') else pb.cmd.gzip

If I use getattr however, it throws `CommandNotFound`. I think if it instead threw an `AttributeError` I could write something like this:

    gzip_cmd = getattr(pb.cmd, 'pigz', pb.cmd.gzip)

I understand that this is changing the API, so it maybe it's out of the question. Maybe it would work if `CommandNotFound` was a subclass of `AttributeError`.

**Comment by henryiii** [comment]
This works now in 1.5.0 (even without the PR).
