### ISSUE TITLE
Access to top-level cli switches when using subcommands

### ISSUE THREAD

**Issue by dsl101** [tomerfiliba/plumbum#194]
This is maybe an extreme case, but I'm looking for a reliable way to get the state of top-level switches when using subcommands, which possibly even call other subcommands (making 'parent' tricky).

In the main top-level def I have:

	no_confirm = cli.Flag(["f", "force"], help="Don't ask for any confirmations")

but then I need to know within a subcommand whether the user included that flag. I guess I can use:

	if not self.parent.no_confirm:
		// etc.

but then I also have this:

	subcommand2.run(['subcommand1', param], False)

so now in subcommand2, the chain is a bit broken - or at least cumbersome. I was hoping there might be some way to write `self.root.no_confirm` or `self.global.no_confirm`. Does anything like that exist currently in plumbum?

**Comment by tomerfiliba** [comment]
there's already root_app -- is that what you're missing?
https://github.com/tomerfiliba/plumbum/blob/master/plumbum/cli/application.py#L141

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>

**Comment by dsl101** [comment]
OK - apologies, and sorry to change the subject then, but it looks like I have an old version! My copy of application.py doesn't have that property, but pip says I'm up to date:

    [root@git: /root] $ pip search plumbum
    pb_job_manager            - A utility class to run plumbum commands in parallel
    plumbum                   - Plumbum: shell combinators library
      INSTALLED: 1.4.2 (latest)

I tried with `--upgrade` but it still says it's already latest. I'm guessing it's the package that's older than the root_app update.

Sorry for being slow on that - Python isn't my regular language. Is it easy to switch to using the github repo? Do I need to build or do anything that `pip` would normally do?

**Comment by edomaur** [comment]
Will we see a 1.4.3 or even a 1.5.0 at some point in time ? It would help in those kind of occurence...

**Comment by henryiii** [comment]
We have a 1.5.0 now. :) Closing.
