### ISSUE TITLE
remote cmd on OSX not working

### ISSUE THREAD

**Issue by chrispella** [tomerfiliba/plumbum#201]
I'm trying to run remote commands on a remote OSX machine (Yosemite).  The ssh connection is up but for some reason plumbum can't find the command. It shows the remote paths correctly. 

```python
 remote['ls']

    194
--> 195         raise CommandNotFound(progname, self.env.path)
    196
    197     def __getitem__(self, cmd):

CommandNotFound: ('ls', [<RemotePath /usr/bin>, <RemotePath /bin>, <RemotePath /usr/sbin>, <RemotePath /sbin>])
```

**Comment by henryiii** [comment]
I can connect just fine to a remote Mac (pretty much left at the default install). 
```python
>>> from plumbum import SshMachine
>>> remote = SshMachine('myserver.edu')
>>> remote['ls']()
'Desktop\nDocuments\nDownloads\nLibrary\nMovies\nMusic\nPictures\nPublic\n'
```

Is this what you are doing?

**Comment by henryiii** [comment]
If there are further problems, please reopen and I'll be glad to help!
