### ISSUE TITLE
Release preperation

### ISSUE THREAD

**Issue by henryiii** [tomerfiliba/plumbum#204]
I'm nearly prepared for release 1.4.3. I just have a few questions:

* Is 1.4.3 the best name? I've prepared a color module in my fork (originally suggested in [#127](https://github.com/tomerfiliba/plumbum/pull/127)) that will probably be submitted as a PR for the next version, probably 1.5.0....?
* Do we still support Python 2.5, 3.0, and 3.1? Travis doesn't list those (and I know the usage of 3.0-3.2 is very low). I'd like to remove anything that is no longer supported from `setup.py` and `docs`.
* Are there any other additions you would like me to update the docs for? I just went through the PR's and updated the changelog for significant ones.

If anything else is needed, let me know. I'll assume you'll change the date in `docs/_news.rst` and `plumbum/version.py` to be the day we make the release, but let me know if you need me to.

**Comment by tomerfiliba** [comment]
it's been over a year since the last release, so why not jump to 1.5 now. you should just update ``version.py`` and tag it in git when you feel it's ready. the ``_news.rst`` is just a "news ticker" for the site, it doesn't matter when we update it.

3.0 and 3.1 are not in use, 2.5 might be. on the other hand, i expected everyone who hasn't moved to 3 to have upgraded to 2.7, so if travis doesn't have it anymore we can safely remove support.

thanks

**Comment by tomerfiliba** [comment]
btw, about color, i always hated the string-pasting approach (e.g., ``print ('%s Hello World !!! %s' % (fg(1), attr(0))``). what i had in mind was more like HTML tags, e.g.

    print "{hello|red} world"

which can be integrated with ``str.format`` (it has hooks)

**Comment by tomerfiliba** [comment]
or rather 

    print "{0|red} world".format("hello")

**Comment by henryiii** [comment]
Travis CI does not have 2.5, and it's not in our `.travis.yml`. Due to the fact that RedHat supported 2.4, then 2.6, 2.5 is really not heavily used in legacy systems. I think RHEL 6 is the main legacy user of 2.6 right now, and they have access to 2.7 through "Software collections", and RHEL 7 ships with 2.7. Supporting 2.6 isn't too hard, though, so not proposing we remove that.

I'm removing written support now. At some point, probably in 1.5.1, I'll go over the code and clean up the 2.5 hacks. `from __future__ import with_statement` can be removed, several parts of the code can have the python 2.5 if statements removed, and `from_future import print_function` can allow normal print functions, rather than the current one argument only `print('')` statements.

I want to check the release on a windows machine before tagging it, so I'll be ready within the next 3 days. Once I tag it, I'm assuming you'll push it to pypi.

**Comment by tomerfiliba** [comment]
sounds great

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>

**Comment by henryiii** [comment]
Tagged.

**Comment by henryiii** [comment]
Fun fact: 2.5 doesn't support decorators. So I doubt the last release or two worked with it. I'll continue to submit new features as PRs, both for your approval and so I have a PR to reference in the Changelog. I'll do doc updates and minor bugfixes directly, unless you recommend something else.

I think you'll really like my new color module. I can't directly change what format does in the way you suggest (it's implemented on a built-in type in C and can't be modified, see PEP 3101, and let me know if I'm wrong). The only way you can tie into "".format is with the part after the `:` in brackets, which isn't very useful for color. You can make a custom string subclass, but that's not intuitive (though I admit, that was my first attempt). I think I have a unique solution that works quite well. It's also becoming incredibly flexible for alternate representations. It's inspired by Plumbum's command syntax and local object. I'll be submitting it as a PR for review soon. (it's in my fork at the moment).
