### ISSUE TITLE
`cwd` messes up the working dir of the caller after exiting `with`

### ISSUE THREAD

**Issue by oconnor663** [tomerfiliba/plumbum#210]
Example Python script:

```python
import tempfile
import os
import plumbum

print("Intial cwd:", os.getcwd())
os.chdir(tempfile.mkdtemp())
print("changed dir to:", os.getcwd())
print("Calling plumbum.cwd()...")
with plumbum.local.cwd('/dev/'):
    pass
print("BUG! The cwd is now back to what it was at the start:", os.getcwd())
```

The problem seems to be here: https://github.com/tomerfiliba/plumbum/blob/53ae73708e9bbb2e520415dd066343321a000b6a/plumbum/path/local.py#L308

`self._path` is cached when the instance is constructed, which happens to be at import time. I think instead `__call__` should call `os.getcwd()` at that line, to get the most up-to-date path.

As a side note, calling `os.chdir()` means that the cwd change will be visible to other threads running in the same process, which makes plumbum not thread safe. If instead plumbum could pass the new path through to the `cwd` named parameter of `Popen`, that might be safer. I haven't read enough of the code to know whether that's practical though.

**Comment by oconnor663** [comment]
Regarding that last note, see also [the warning in the docs for `contextlib.redirect_stdout`](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout):

> Note that the global side effect on sys.stdout means that this context manager is **not suitable for use in library code and most threaded applications.**

**Comment by henryiii** [comment]
Try the current checkout, I think I fixed this a week or two ago. I'll be back in a few days and I'll check then.

**Comment by oconnor663** [comment]
Yep, looks good now. Thanks.
