### ISSUE TITLE
Colors: Default style suggestions

### ISSUE THREAD

**Issue by henryiii** [tomerfiliba/plumbum#215]
Added `default_styles` in `colorlib/names.py`, and user stylesheets can be loaded too. Any suggestions (from anyone) for the default styles? Either new styles or different colors/attributes for current styles. Here's the current one that I quickly threw together:

```python
default_styles = dict(
    warn="fg red",
    title="fg cyan underline bold",
    fatal="fg red bold",
    highlight="bg yellow",
    info="fg blue",
    success="fg green",
    )
```

Note: to quickly test these, for example `warn`, simply use the following command on the command line:
```bash
$ python -m plumbum.colors warn
```

You can also test the style before submitting it:
```bash
$ python -m plumbum.colors fg red bg 123 underline bold
```

And reset:
```bash
$ python -m plumbum.colors
```

Also, anything in the library, including 24 bit color, is available, though sticking to a smaller subset of colors (8, 16, or 256) is more universally usable. For example, colorama only supports the first 16.

**Comment by hellerve** [comment]
Maybe add `success="fg green"` to the default styles? Other than that, I as a user am happy.

**Comment by henryiii** [comment]
Thanks! Added success and info (blue).

**Comment by hellerve** [comment]
Sounds good :+1: Can't wait for the next version.

**Comment by henryiii** [comment]
Version 1.6.0 tagged, closing.
