### ISSUE TITLE
v1.5.0 broken on Python3.5

### ISSUE THREAD

**Issue by hellerve** [tomerfiliba/plumbum#222]
Hey,

we are using an internal script for deployment and recently upgraded to Python3.5. Now however our script fell over, in our case because of [that particular line](https://github.com/tomerfiliba/plumbum/blob/a690a3f3d1a4b3af7c1812bf76dd31aafacd5195/plumbum/machines/local.py#L231), because `subprocess` module doesn't have a `mswindows` property anymore. I see that this function has changed since. I don't know about the rest of the code.

All of that said, my issue boils down to this question:
Any hope on the next release to be Py-3.5 compatible?

**Comment by tomerfiliba** [comment]
sure, it's supposed to be. @henryiii are you aware of that mswindows incompatibility?

**Comment by henryiii** [comment]
I fixed Py 3.5 compatibility a few days ago. 1.6.0 will fully support Python 3.5. See #218

**Comment by hellerve** [comment]
Damn cool :+1: Thanks for the quick reply, guys!

**Comment by henryiii** [comment]
@tomerfiliba Yes, it's even mentioned in the original PR. :smile:  There were other Py 3.5 fixes, too.
@hellerve, if you try the latest build, let me know if you encounter any problems.

**Comment by tomerfiliba** [comment]
@henryiii -- yeah, sorry, we had a race condition replying to this issue :)

**Comment by hellerve** [comment]
I will do so. Our script is not tapping into a whole lot of plumbums features, though, so don't take it as a guarantee if I don't run into any problems. :wink:

**Comment by henryiii** [comment]
v1.6.0 should be fully Python 3.5 compatible.
