### ISSUE TITLE
Planning for 1.6.0

### ISSUE THREAD

**Issue by henryiii** [tomerfiliba/plumbum#224]
I'd like to record my plans for the 1.6.0 release. Since 1.5.0 doesn't support Python 3.5, we need a release fairly soon. I can patch small fixes to make a 1.5.1 release, but I think it is probably better to do a 1.6.0, and just be ready to do a 1.6.1 if any show stoppers come up.

Here are the things I'd like to finish before we do a 1.6.0:

- [x] Remove/simplify a little more syntax from `plumbum.colors` (like `__call__` on a style)
- [x] Add positional argument validators #225 
- [x] Look at cutting back on `.COLOR*` properties for `cli.Application`, instead see if things like the program name can simply be specified with a color.
- [x] Allow more pathlib path behavior (with a few new features, like uri's) #223 
- [x] Test on Windows, check Windows/Paramiko related issues

I'm thinking of going to bug fixes only at the end of this week, and aiming for a release soon after.

I'm hoping I'll be able to work on argument completion support for 1.7.0 (I might not have time to work on this for a while). #212 

Anyone, feel free to update or comment.

**Comment by henryiii** [comment]
The `*.COLOR` properties is the only thing I have left (and maybe the string path patch), then if all is well I'll prepare 1.6.0.

**Comment by henryiii** [comment]
I've changed the way colors in cli works, hopefully to a much more intuitive and simple method. In several cases, you can just set the color on the string itself. I forgot to add docs/update other examples, will do that soon.

**Comment by henryiii** [comment]
@tomerfiliba, I'm ready for 1.6.0; if we want to wait for a little while to see if any issues come up, or if you have any recommendations, let me know. I'll commit the 1.6.0 preparation commit and tag it when you give the go-ahead.

**Comment by henryiii** [comment]
I can disable the `str` subclassing for this release if you want to extend the discussion on whether to subclass `str` or not, otherwise, we are ready to go.

**Comment by tomerfiliba** [comment]
the reason i chose not to make path a subclass of str in the first place
was for LocalPath and RemotePath having the same semantics. on the other
hand, you can't open(str(rem_path)) so there's no real source for
confusion. you can go ahead and tag the release

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>

**Comment by tomerfiliba** [comment]
uploaded to pypi

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>
