### ISSUE TITLE
Colors don't apply inside gnu screen session in konsole

### ISSUE THREAD

**Issue by AndydeCleyre** [tomerfiliba/plumbum#231]
Hi,

Using the 1.6.0 release and the following script, the plumbum-colored strings don't appear colored inside a screen session inside konsole, though they do outside of screen.

Here's my `.screenrc`:
```yaml
escape ``
bind "j" prev
bind "k" next
bind "l" screen
defscrollback 300000
termcapinfo xterm ti@:te@
msgwait 2
````

And here's the script (see last few lines):
```python
#!/usr/bin/env python3

from sys import argv
from time import time
from random import random

from plumbum import local
from plumbum.colors import red as pred, green as pgreen
from clint.textui.colored import red, green


EDITOR = local['subl']['-w']


if __name__ == '__main__':
    initial_names = argv[1:]
    with local.tempdir() as tmp:
        name_file = tmp / 'txtnamer_{}_{}_{}'.format(local.cwd.basename, time(), random())
        name_file.write('\n'.join(initial_names).encode())
        EDITOR(name_file)
        lines = name_file.read().decode().strip().split('\n')
    if len(lines) == len(initial_names):
        for file, dst in zip(map(local.path, initial_names), lines):
            if file.basename != dst:
                print(red(file.basename), green(dst), '', sep='\n')# clint, works inside screen
                print(pred | file.basename, pgreen | dst, '', sep='\n')# plumbum, doesn't work inside screen
                file.move(dst)
````

**Comment by henryiii** [comment]
Plumbum's color library looks for the `$TERM` variable to try to set color on or off. Can you try `echo $TERM` in a shell? I get `screen` as the result. I'm not sure whether color should always be on for `screen`, though.

clint uses `.isatty()` only, and then has an environment variable that can be set. Maybe it would make sense to assume at least basic color output if `$TERM` is not xterm, etc.

You can enforce color using:
```python
from plumbum import colors
colors.use_color = 3 # 0 is off, 1 is 8 color, 2 is 16, 3 is 512, and 4 is 24 bit color
```
And that will turn on color regardless of the terminal type.

**Comment by AndydeCleyre** [comment]
Thanks, it's `screen` for me as well, and setting `use_color` works. I would support color working inside screen by default, but I'm not sufficiently familiar with the potential problem cases.

**Comment by henryiii** [comment]
Found the docs on screen, and did some testing. Screen forces 8 color mode default, so added that plumbum.colors, and you can set `term screen-256color` to get 256 color mode, so added support for that too. Also changed the default to be level 3 color vs. no color, unless of course `isatty()` is false.

**Comment by AndydeCleyre** [comment]
Looks great, thanks!
