### ISSUE TITLE
CLI subcommand "help" instructions are annoying

### ISSUE THREAD

**Issue by markerikson** [tomerfiliba/plumbum#232]
Running a cli.Application command with a "-h" currently prints out a "see 'myScript.py subcommand --help' for more info" message for every subcommand.  I personally find this to be annoying and unnecessary.  Would it be possible to make this optional somehow?

**Comment by henryiii** [comment]
I can look at this in a few days, I'd be open to it. If you have any ideas on how best to do it, feel free to try it out and let us know.

**Comment by markerikson** [comment]
Looks good so far.  Thanks for the quick response!
