### ISSUE TITLE
Windows list_processes() Unicode error

### ISSUE THREAD

**Issue by markerikson** [tomerfiliba/plumbum#235]
I'm getting this error trying to call `local.list_processes()` on a Win7 machine under Python 2.7:

```
  File "../../lib/python\plumbum\machines\local.py", line 333, in pgrep
    for procinfo in self.list_processes():
  File "../../lib/python\plumbum\machines\local.py", line 311, in list_processes
    for row in rows:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfd' in position 104: ordinal not in range(128)
```

I was able to hack around it by making this edit to local.py to force output conversion:

```python
            output = tasklist("/V", "/FO", "CSV")
            output = output.encode('ascii', 'ignore')
            lines = output.splitlines()
```

Any better ideas would be appreciated.

**Comment by henryiii** [comment]
Windows is a unicode system, so it allows unicode filenames. I believe the correct solution would be to fix plumbum to handle unicode process names. It can be a little tricky to handle both types of systems., I think. I'll look into it in a few days, fell free to look at it too.

**Comment by henryiii** [comment]
Correction: csv on Py2.7 is the probable culprit, it doesn't handle Unicode. It hopefully is easy to remove the csv module usage here.

**Comment by henryiii** [comment]
I can't repeat the error, since all the unicode chars I use turn into (incorrectly) encoded chars. Do you know what symbol is in your process list that's causing the error? I can't turn `u'\xfd'` into a printable char to make a fake process from.
