### ISSUE TITLE
Override

### ISSUE THREAD

**Issue by henryiii** [tomerfiliba/plumbum#245]
While working on extending the test coverage, I noticed that the `override` parameter of `.copy` didn't actually do anything; it deleted the file before copying to the new location, but the underlying copy operation copied even if the file existed, so it was meaningless. I've fixed it to throw an error in the pytest branch, but that raises a further question: we should support a single method for choosing what is done on copy/move/etc, so should it be: 
- an override parameter, that can be `True`, `False`, or `None`, throwing an error if `False`, and silently ignoring the failed copy/move if `None`. The default would be `True`, since the current `False` acts like `True`. (Open to discussion!). This would be uniformly implemented on all copy and move functions.
- Other suggestions?

**Comment by henryiii** [comment]
Correction: it does change what happens if the path is a directory. I will restore (and document/test!) the current behavior, and then look at adding an "overwrite" parameter or method of some sort. Suggestions still open.

**Comment by jixx** [comment]
@henryiii maybe the Code got messed up in commit 6012d80d5e3782170fa089a7c23e00e84336e061?

Currently the code checks for overwrite:
`if not overwrite and dst.exists():` but if the expression is true (file exists and `overwrite` is false), we get the hint that `override` was not specified. At least here is a typo (override != overwrite).

But i must admit that i don't quite get it what you are trying to achieve with override and overwrite. Reading your comment i think 
`override == None` is for the case that i don't want to overwrite an potentially existing file, but also don't want an exception if the file really exists (silently failing copy operation if file exists).
`override == False` will throw an exception if `overwrite == False` and `dst.exists()`, but what is the meaning of 
`override == True` then?

**Comment by AndydeCleyre** [comment]
This is still a confusing situation, having path `copy` accept both `overwrite` and `override`, with opposite defaults, no relevant docstring, and a therefore unpredictable behavior.

**Comment by henryiii** [comment]
At the moment I can't remember what in the world I was thinking here... I think I was trying to provide backward compatibility and move forward with a new and better way to specify things, but without any doc strings I'm quite confused as to what I was thinking.

**Comment by henryiii** [comment]
Please let me know if that PR looks good.
