### ISSUE TITLE
v1.6.1

### ISSUE THREAD

**Issue by henryiii** [tomerfiliba/plumbum#247]
I think we are about ready for a 1.6.1 release. I'll be tagging any new (non-fix) PRs or issues with 1.6.2 now, and if there appear to be no major issues, I'd like to call for a 1.6.1 release in about a week. There are several significant fixes since 1.6.0 that I think should be made available soon.

**Comment by henryiii** [comment]
Tagged and pushed 1.6.1.

**Comment by henryiii** [comment]
Pypi doesn't have v1.6.1 atm.

**Comment by henryiii** [comment]
@tomerfiliba, If you want me to help with the pypi release, my pypi username is the same as my github one.

**Comment by tomerfiliba** [comment]
you've been added. thanks. sorry i don't have time to maintain the project
:(

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com     <http://www.facebook.com/tomerfiliba>
<http://il.linkedin.com/in/tomerfiliba>

**Comment by henryiii** [comment]
Had an issue where the `build.py` script errored out, not sure why. Re-uploaded manually with `setup.py` to `1.6.1.post0`.
