### ISSUE TITLE
Unicode decoding error when using TEE combinator

### ISSUE THREAD

**Issue by nicholashaydensmith** [tomerfiliba/plumbum#248]
I get the following error when using the TEE combinator on a make command:

```
  File "my_prog.py", line 174, in run
    (ret, stdout, stderr) = make_cmd & TEE(retcode=None)
  File "/usr/local/lib/python3.4/dist-packages/plumbum/commands/modifiers.py", line 189, in __rand__
    tee_to[fd].write(data.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 4094-4095: unexpected end of data
```
The offending plumbum code from modifiers.py:
```
183                     data = os.read(fd.fileno(), 4096)
184                     if not data:  # eof
185                         continue
186 
187                     # Python conveniently line-buffers stdout and stderr for
188                     # us, so all we need to do is write to them
189                     tee_to[fd].write(data.decode('utf-8'))
```

It seems like gcc is using some unicode characters and `os.read(fd, 4096)` is splitting a unicode character in half at the 4095th byte boundary.  I've attached a contrived example of a file that has a unicode character in this position to expose this bug. [unicode.txt](https://github.com/tomerfiliba/plumbum/files/56041/unicode.txt)

```
import os
fd = os.open('unicode.txt', os.O_RDWR)
os.read(fd, 4096).decode('utf-8')
```

**Comment by henryiii** [comment]
Nice catch! Is there a standard way to read utf data in, for example, variable chunks? I'll be able to take a look at this in a few days.

**Comment by nicholashaydensmith** [comment]
I'm not sure, I've been looking around stackoverflow, but it hasn't been very fruitful. Someone said to use `decode('utf-8', errors='ignore')`, which will just drop the bytes it wasn't able to decode, but that's probably not a great solution.  Here is a useful snippet from the python docs that suggests using a try catch block for this case or to use the codecs lib https://docs.python.org/2/library/codecs.html:

> One problem is the multi-byte nature of encodings; one Unicode character can be represented by several bytes. If you want to read the file in arbitrary-sized chunks (say, 1K or 4K), you need to write error-handling code to catch the case where only part of the bytes encoding a single Unicode character are read at the end of a chunk. One solution would be to read the entire file into memory and then perform the decoding, but that prevents you from working with files that are extremely large; if you need to read a 2Gb file, you need 2Gb of RAM. (More, really, since for at least a moment you’d need to have both the encoded string and its Unicode version in memory.)

>The solution would be to use the low-level decoding interface to catch the case of partial coding sequences. The work of implementing this has already been done for you: the codecs module includes a version of the open() function that returns a file-like object that assumes the file’s contents are in a specified encoding and accepts Unicode parameters for methods such as .read() and .write().

**Comment by henryiii** [comment]
Does something like this work? utf-8 can be from 1-4 bytes, if I remember correctly, so this should cover all cases...

```python
                    # Python conveniently line-buffers stdout and stderr for
                    # us, so all we need to do is write to them

                    # This will automatically add up to three bytes if it cannot be decoded
                    for i in range(4):
                        try:
                            tee_to[fd].write(data.decode('utf-8'))
                            break
                        except UnicodeDecodeError:
                            data += os.read(fd.fileno(), 1)

```

**Comment by henryiii** [comment]
That trick works on your example. It does look a little ugly, though, I like to avoid `break`. Also, it doesn't finally call the exception if it fails 4 times...

**Comment by nicholashaydensmith** [comment]
Yeah works for me too and on my original make command.  I can't think of a cleaner way to do it, but I'm no python wizard.  Thanks man!

**Comment by henryiii** [comment]
Try master, does that also work?

**Comment by nicholashaydensmith** [comment]
There is a typo, commented inline, but with that fixed it works for me.
