### ISSUE TITLE
Path class should support join operations

### ISSUE THREAD

**Issue by mjmonroe** [tomerfiliba/plumbum#250]
The [Path's](https://github.com/tomerfiliba/plumbum/blob/28cdb53999e28164a43733c3db8c3dabcef45d09/plumbum/path/base.py)  class join method is abstract and relies on a subclass to implement it. I use the class to create generic Paths, then later on in my code decide whether or not to make then remote or local. It would be nice if the Path join method worked.

My join function, of which slight modification could be used to replace the empty Path.join method.
```
import os
from plumbum.path import Path

def join_paths(path1, path2):
    return Path(os.path.join(path1, path2))
```

**Comment by henryiii** [comment]
`os.path.join` doesn't do the correct thing when joining a remote path on a different filesystem, so to me this looks like a good way to have a potential bug.

If you are sure the same separator is used, can't you just subclass `Path` with that method changed?

**Comment by henryiii** [comment]
Feel free to reopen this if there is a good reason that Path subclass will not work as well!
