### ISSUE TITLE
Error unpickling LocalPath using jsonpickle

### ISSUE THREAD

**Issue by mjmonroe** [tomerfiliba/plumbum#251]
Jsonpickle.dumps produces a string like this:
`{"py/object": "plumbum.path.local.LocalPath", "py/state": {"_path": "/data/holder/for_mark"}, "py/newargs": {"py/tuple": ["/data/holder/for_mark"]}}}` To unpickle the object there needs to be a way to set the _path property of LocalPath otherwise a set attribute error is thrown.

```
    @property
    def _path(self):
        return str(self)
    #Needed to allow jsonpickle to unpickle the object
    @_path.setter
    def _path(self, value):
        return None

    def _get_info(self):
        return self._path
    def __getstate__(self):
        return {"_path" : self._path}
```

**Comment by henryiii** [comment]
So why is `_path` special? The other computed properties don't need to be "set"... I'll look into this more in the next couple of days, as I just got back.

**Comment by henryiii** [comment]
This seems to work properly now that there is no "_path" property, just a computed property.
