### ISSUE TITLE
Add TEE to __init__.py so it can be imported like FG, RETCODE and others 

### ISSUE THREAD

**Issue by DanielJoyce** [tomerfiliba/plumbum#255]
cf https://github.com/tomerfiliba/plumbum/pull/117

Should be added to line 38 in __init__.py

from plumbum.commands import FG, BG, TF, RETCODE, ERROUT, NOHUP

Right now, 'from plumbum import FG" works, but "from plumbum import TEE" fails

**Comment by henryiii** [comment]
I just got back in the states. Will try to address this tomorrow!
