### ISSUE TITLE
Reset color string, with use of "color"

### ISSUE THREAD

**Issue by hfr** [tomerfiliba/plumbum#256]
In Version 1.6.1 there is a reset color sequence (`<esc>[0m`) send to the terminal even if no color is used when an cli application terminates.

The reason is the line
```
0017:    atexit.register(_reset)
```
in module colors.py.

While this might not hurt most of the time, it looks funny on Windows machines, where the sequence is not handled correctly out of the box.

Obviously the call of `_reset()` is very useful to reset the terminal if any color-functions are used. But a better way is needed to decide when it should be called.

Rüdiger

**Comment by henryiii** [comment]
The problem is that it is incorrectly allowing color on a terminal that does not support it; a temporary fix is to set `use_colors` to `False` or `0`. What is the value of `%TERM%`?

**Comment by hfr** [comment]
Env %TERM% is usually not defined on Windows machines.

2016-01-20 15:28 GMT+01:00 henryiii <notifications@github.com>:

**Comment by henryiii** [comment]
Okay, I actually test against `os.name == 'nt'`. I set `use_color` to 1, since I'm assuming colorama or other is installed. I probably should set `use_color` to 0 then force manual activation when loading colorama, etc? I'll play with this when I'm on a computer.

**Comment by hfr** [comment]
changing:
    elif os.name == 'nt':
        return 0
in stypes.py did the trick.
User who want colors on Windows could set the env TERM=screen or set
colors.use_color=1 in the script.
This way it will be backward compatible...

2016-01-20 18:28 GMT+01:00 henryiii <notifications@github.com>:
