### ISSUE TITLE
RemoteCommands and nohup

### ISSUE THREAD

**Issue by magixx** [tomerfiliba/plumbum#261]
As far as I can tell attempting to run a command remotely via nohup is broken. 
ex:
[plumbum/machines/remote.py](https://github.com/tomerfiliba/plumbum/blob/master/plumbum/machines/remote.py#L117)
```python
    def nohup(self, cwd='.', stdout='nohup.out', stderr=None, append=True):
        """Runs a command detached."""
        return machine.nohup(self, cwd, stdout, stderr, append)
```
The referenced machine in nohup would need to be self.machine. However even with that change there seems to be the issue that SshMachine.nohup takes in completly different parameters and seems to getting deprecated. ex:
[plumbum/machines/ssh_machine.py](https://github.com/tomerfiliba/plumbum/blob/master/plumbum/machines/ssh_machine.py#L128)
```python
    def nohup(self, command):
        """
        Runs the given command using ``nohup`` and redirects std handles,
        allowing the command to run "detached" from its controlling TTY or parent.
        Does not return anything. Depreciated (use command.nohup or daemonic_popen).
        """
        warnings.warn("Use .nohup on the command or use daemonic_popen)", DeprecationWarning)
        self.daemonic_popen(command, cwd='.', stdout=None, stderr=None, append=False)
```

Remote nohup should then perhaps be calling `daemonic_popen` of machine with proper parameters.

**Comment by henryiii** [comment]
So does the following new version work? It should, from a cursory glance:

```python
    def nohup(self, cwd='.', stdout='nohup.out', stderr=None, append=True):
        """Runs a command detached."""
        return self.machine.daemonic_popen(self, cwd, stdout, stderr, append)
```

**Comment by henryiii** [comment]
Assuming fixed.

**Comment by mbarkhau** [comment]
Doesn't the method `commands.base.BaseCommand.nohup` suffer from the same issue.

https://github.com/tomerfiliba/plumbum/blob/master/plumbum/commands/base.py#L139

**Comment by mbarkhau** [comment]
I'll just invoke the `daemonic_popen` myself for now.
