### ISSUE TITLE
Documentation for local 

### ISSUE THREAD

**Issue by davidedelvento** [tomerfiliba/plumbum#276]
It looks like there is no API doc for local(), the one it's imported with `from plumbum import local` since from http://plumbum.readthedocs.io/en/latest/index.html#api-reference only subpackages are documented and not the plumbum package itself.

**Comment by henryiii** [comment]
It's actually an instance of a `plumbum.machines.local.LocalMachine`, so it is documented there.

**Comment by henryiii** [comment]
Let me know if you think a note similar to that in the docs somewhere would be helpful.

**Comment by davidedelvento** [comment]
Yes, I think a note about that in the docs would be very useful. Thanks
