### ISSUE TITLE
argument 0 should not be ignored

### ISSUE THREAD

**Issue by AlexeyDmitriev** [tomerfiliba/plumbum#277]
So when you pass zero as a command it got skipped

```
>>> from plumbum.cmd import echo
>>> echo(5)
'5\n'  #ok
>>> echo(3)
'3\n' #ok
>>> echo(0)
'\n' #what?!
>>> echo('0')
'0\n' #fixes it
```

I don't think it should because in that case you now have to call str for each your object.

As I noticed, empty string is not skipped that way(and that's cool or you wouldn't be able to call equivalent of bash `command ""`)

BTW, I didn't find in the docs information about this behaviour. Is it intended to skip None's? So, probably `arg is None` should be iffed

**Comment by henryiii** [comment]
I'll take a look at it in the next day or two. I've just finished my doctorate, so should have time to do a little issue clean up and prepare a release soon.
