### ISSUE TITLE
Doc plumbum.cli.CountingAttr does not exsist

### ISSUE THREAD

**Issue by boeddeker** [tomerfiliba/plumbum#294]
In the Documention [cli.rst](https://github.com/tomerfiliba/plumbum/blob/master/docs/cli.rst) is CountingAttr used, but it does not exist. Maybe the correct name is CountOf?

**Comment by henryiii** [comment]
Nice catch, a quick `git grep CountingAttr` shows that the change log is the only other place `CountingAttr` shows up, and it was renamed to `CountOf`. I think I like the old name better, but I'll fix the docs.
