### ISSUE TITLE
Globbing in background command arguments

### ISSUE THREAD

**Issue by andrewbaxter** [tomerfiliba/plumbum#296]
The following can't be used, and I don't see a nice alternative:

```
wc['-l',*glob('*.bin')] & BG
```

Also, I've heard that multi-argument `__getitem__` is deprecated in Python 3.

**Comment by henryiii** [comment]
Multi-argument `__getitem__` is fine, arrays with more than one dimension in numpy will always be supported, for example. I do remember a discussion about adding keyword arguments but don't think it went anywhere.

An obvious but hideous workaround is:
```python
wc.__getitem__(('-l',) +tuple(glob('*.bin'))) & FG
```

But why not use plumbum all the way, no workarounds needed:
```python
wc['-l', local.cwd // '*.bin'] & bg
```

Personally, I'm thinking refactoring `__getitem__` into a named method, then making `__getitem__` simply call that method might be a good idea.

**Comment by henryiii** [comment]
Added suggestion mentioned.
