### ISSUE TITLE
git subcomands

### ISSUE THREAD

**Issue by gamaanderson** [tomerfiliba/plumbum#301]
when I run:

    plumbum.local['git']('pull origin master')

I get the `git: 'pull origin master' is no Git command` error, this is obvious because of those quote marks. Is there a way around, or is the an other way of running  `git` with plumbum?

**Comment by henryiii** [comment]
Try separating the three words as comma separated strings?

**Comment by henryiii** [comment]
```
plumbum.local['git']('pull', 'origin', 'master')
```

**Comment by gamaanderson** [comment]
that worked, thank you
