### ISSUE TITLE
Plumbum 1.6.4 requires setuptools

### ISSUE THREAD

**Issue by henryiii** [tomerfiliba/plumbum#357]
Plumbum 1.6.4 requires setuptools to load the translations. This should either be explicitly stated as a requirement, the setuptools requirement dropped, or translations simply don't load without setuptools. 

Since the Python packaging system is built around setuptools these days, it's probably not a critical issue. Correct me if I'm wrong.

**Comment by KOLANICH** [comment]
Since we are already using setuptools I guess we need also to move the metadata into setup.cfg

**Comment by henryiii** [comment]
Should be fixed by #367, non-setuptools should work again (not really tested though, since a non-setuptools Python is a bit hard to come by, at least for me when working in virtual envs)
