### ISSUE TITLE
get stdout from a running command - unified api for local and remote

### ISSUE THREAD

**Issue by rugubara** [tomerfiliba/plumbum#358]
I'm struggling with adapting my app to ssh remote targets.
I used  subprocess.run to get the stdout out of a local command.
I have a list of targets to run the same command, these targets may be local or remote. I receive the prepared command object as a parameter.
I tried to apply the same method to both SshMachine and ParamikoMachine. Neither of them work this way. What's the best approach to run a command and process its stdout, regardless of where it happens: locally or via ssh?

**Comment by henryiii** [comment]
Do you need a stream or is a string okay? (You can just call a command with `()` and you get the stdout as a string, if that's all you need)

**Comment by rugubara** [comment]
Well, I need to feed it into csv.reader - so I need a thing with an iterator. If you can quickly advise, it would save me a ton of searching on how to convert a string to a list of lines (strings)

**Comment by henryiii** [comment]
Very quickest hack to get it working: just do `my_command().splitlines()` to call the command, produce a stdout string, and then split into lines. That won't work well with a slow command that produces lines as it runs that you want to process in real time, but otherwise will work fine, I think...

**Comment by henryiii** [comment]
Maybe better solution: use `.popen()` on the command; that gives you an iterator that can produce a list of lines (the final item of the iterator is `None`)

**Comment by henryiii** [comment]
This example works locally and will also work remotely:

```python
from plumbum.cmd import echo
prepared_command = echo['1,2\n3,4\n5,6']
reader = csv.reader(prepared_command().splitlines())
for line in reader:
     print(line)
```

(If this were a real piece of code, I'd use this instead:
```python
from plumbum.cmd import echo
reader = csv.reader(echo('1,2\n3,4\n5,6').splitlines())
for line in reader:
     print(line)
```
)

**Comment by rugubara** [comment]
Yes, it seems so for me too. I'll test when I get home to get some meaningful returns from ssh-ing to my home machine. Thanks for help!

**Comment by rugubara** [comment]
Works for me. Thanks for your help.
