### ISSUE TITLE
Translations loading is damn slow

### ISSUE THREAD

**Issue by KOLANICH** [tomerfiliba/plumbum#364]
It slows down every program using plumbum a lot. I guess it should be disabled by default.

**Comment by henryiii** [comment]
Do you have an example so I can test and fix? Complex app or all (including simple) apps? How slow?

**Comment by KOLANICH** [comment]
All apps. When I run an app using plumbum, there is a delay. If I hit ctrl+c during this delay, I get the KeyboardInterrupt exception, and this exception is likely  to be in the code loading translations.

**Comment by henryiii** [comment]
Should be fixed in b7222f87f338f4ef1a0c8262d748a2bad93b5f0d. For me, the simple example went back down to 200 ms (like in 1.6.3) from 320 ms or so in 1.6.4 when using English.
