### ISSUE TITLE
SyntaxError in plumbum/cli/image.py

### ISSUE THREAD

**Issue by grozin** [tomerfiliba/plumbum#365]
image.py contains the line

import . as cli

All versions of python I tried (3.6, 3.5, 2.7) raise SyntaxError reading this line. According to the Python Language Reference, such syntax of the import statement is not allowed. What exactly is the purpose of this line? And how to achieve this purpose in legal python?

**Comment by grozin** [comment]
Is the following patch OK?
[patch.txt](https://github.com/tomerfiliba/plumbum/files/1562113/patch.txt)
Argh, this site does not like .patch files, had to rename it.

**Comment by tkluck** [comment]
With certain versions of `pip`, this will actually break the installation of Plumbum entirely, because those versions have a hard dependency on the `py->pyc` step succeeding. (This happened at one of my work deployments; don't have the logs on me atm.)

**Comment by tkluck** [comment]
@grozin if that patch works (I haven't verified it), maybe you can submit it as a pull request, instead? That maximizes the chances of it being picked up.

**Comment by tkluck** [comment]
@grozin never mind, I found a smaller patch and submitted that as a pull request. Thanks for opening this issue!
