### ISSUE TITLE
"IndexError: tuple index out of range" on missing arguments

### ISSUE THREAD

**Issue by Ragnoroct** [tomerfiliba/plumbum#371]
![image](https://user-images.githubusercontent.com/19155205/34913485-79a6fe3a-f8c4-11e7-8771-2f6066a9bba6.png)

When trying to run a subcommand without the correct amount of arguments I get a python exception.

Using conda and python 3.6
plumbum version: - plumbum=1.6.5=py36_0

**Comment by laktak** [comment]
I'm having the same issue.

Workaround for now:
```
pip3 install --user 'plumbum==1.6.4' --upgrade
```

**Comment by henryiii** [comment]
Could you copy and paste a little example code to show the problem? It looks like you had a 27 line example from the screen shot. Would expedite preparing a fix.

**Comment by Ragnoroct** [comment]
laktak's solution worked.

This is my code.

`#!/c/Users/Willy/Miniconda3/envs/scraper/python

from plumbum import cli
from plumbum import local
from pathlib import Path
import os
from scraper.scraper import scrape

class Toolman(cli.Application):
    verbose = cli.Flag(["v", "verbose"], help = "If given, I will be very talkative")

    def main(self):
        pass

@Toolman.subcommand("scrape")
class Scrape(cli.Application):
    """Scrapes the bls.gov website for data"""
    cache = cli.Flag(["c", "cache"], help = "Use sqlite3 cache for responses.")

    def main(self):
        print("Beginning Scraping")
        scrape(self.cache)
        print("Scraping Finished")

@Toolman.subcommand("deploy")
class Deploy(cli.Application):
    """Deploys Master Origin Branch -> Host defined in ~/.ssh/config"""

    def main(self, host):
        print(f"Deploying to {host}")
    
@Toolman.subcommand("validate")
class Validate(cli.Application):
    """Validates Series Data"""

    def main(self, dirPath):
        print("Validating:", dirPath)

        #Check if absolute path
        if not os.path.isabs(dirPath):
            pwd = local["pwd"]
            pwdPath = pwd().replace('\n', '')
            dirPath = os.path.normpath(os.path.join(pwdPath, dirPath))  
        print("Checking:", dirPath)

if __name__ == "__main__":
    Toolman.run()`

**Comment by henryiii** [comment]
@Ragnoroct, have you tried the latest master? It should be fixed there.

**Comment by laktak** [comment]
@henryiii could you push the fix to pypi? thanks

**Comment by henryiii** [comment]
Should be pushed to pypi now.

**Comment by laktak** [comment]
Works great, thanks!
