### ISSUE TITLE
__fpath__ not required

### ISSUE THREAD

**Issue by RazerM** [tomerfiliba/plumbum#396]
`Path` has a `__fpath__` method:
https://github.com/tomerfiliba/plumbum/blob/118ea1bba9f1d817fc7f476364569cf11d0f4e8f/plumbum/path/base.py#L87-L89

The correct method name is `__fspath__`, but since `Path` inherits from `str` it would never be called: [cpython/Lib/os.py#L1039](https://github.com/python/cpython/blob/ea68d83933e6de6cabfb115ec1b8888301947369/Lib/os.py#L1039)

**Comment by henryiii** [comment]
Yes, but `fspath` is still a good idea IMO if someone calls it manually or if the string inheritance is eventually removed. The name does need to be fixed, though! Thanks!
