### ISSUE TITLE
Recommended way to "nice" an executable?

### ISSUE THREAD

**Issue by presto8** [tomerfiliba/plumbum#400]
Hello, I recently found plumbum and love the concept! 

One thing I don't see covered in the documentation and wondering if it's been addressed before is how to "nice" a process. This is quite trivial in bash, e.g.

    nice ffmpeg [...]

However, in plumbum, it would have to be:

    nice = local['nice']
    nice('ffmpeg', ...)

Which is technically correct, but it loses quite a bit of readability in the code.

Thanks!

**Comment by AndydeCleyre** [comment]
I can't tell what the difference in readability is, but if it's that first line, you could alternatively have this among your imports:

```python
from plumbum.cmd import nice
```

**Comment by presto8** [comment]
Thanks! I ended up doing this, and it works! Issue resolved!

   from plumbum.cmd import nice
   ffmpeg = nice['ffmpeg']
   ffmpeg(...)

What I meant by readability was that it's nice to have the variable name be the name of the command. I didn't realize I could just append more arguments and they would all get appended together.

**Comment by henryiii** [comment]
Great. :)
