### ISSUE TITLE
Docs report different output than execution

### ISSUE THREAD

**Issue by apnewberry** [tomerfiliba/plumbum#412]
https://plumbum.readthedocs.io/en/latest/local_commands.html#input-output-redirection says 

> `grep["world"] < sys.stdin > "tmp.txt"` would result in False

but in Plumbum 1.6.7 on Python 3.6.5 I get 

`TypeError: '>' not supported between instances of '_io.TextIOWrapper' and 'str'`

This seems like a good thing -- I'd much rather get an exception than a silent mistake. 

Am I misreading the docs here?

**Comment by smheidrich** [comment]
It returns ``False`` only when using Python 2; the docs should be updated to say that it raises an exception in Python 3.
