### ISSUE TITLE
Stream binary data from stdout

### ISSUE THREAD

**Issue by brianbienvenu** [tomerfiliba/plumbum#425]
I'm making a Flask app which passes around large binary blobs (up to 250MB). It might transparently decompress a bz2 (I'm doing this with `bz2.BZ2File`), or it might pass that binary data through a local console application for other processing. I'm trying to use plumbum for the latter.

I can almost get what I want using `chain.popen().iter_lines()` or `chain.proc.iter_lines()`, but these are clearly intended to return a string line-by-line, instead of a binary object.

As an example, A `bz2.BZ2File()` returns a file-like object, which can be streamed out:

    >>> z = bz2.BZ2File('test.bz2')
    >>> for l in z:
    ...     print(l)
    ...
    b'\x01\x00\x01\x00"\xa4\x00\x000\x00\x00\x00\x06\x00\x00\x00ra...'
    b'\x00\x0b\x00\x0c\x00\r\x00\x0e\x00\x0f\x00\x10\x00\x11...'

This is the closest to data streaming that I've gotten out of plumbum so far:

    >>> chain = (bzcat < 'test.bz2') & BG
    >>> for l in chain.proc.iter_lines(linesize=1):
    >>>    print(l)
    ['\x01', None]
    ['\x00', None]
    ['\x01', None]
    ['\x00', None]
    ['"', None]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.7/dist-packages/plumbum/commands/processes.py", line 271, in iter_lines
        for t, line in _iter_lines(proc, decode, linesize):
      File "/usr/local/lib/python3.7/dist-packages/plumbum/commands/processes.py", line 50, in _iter_lines
        for ret in selector():
      File "/usr/local/lib/python3.7/dist-packages/plumbum/commands/processes.py", line 48, in selector
        yield key.data, decode(key.fileobj.readline(linesize))
      File "/usr/local/lib/python3.7/dist-packages/plumbum/commands/processes.py", line 264, in <lambda>
        decode = lambda s: s.decode(encoding).rstrip()
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid start byte

The data processing rate is about the same as the internet download speed, so I would prefer to not call `chain()` and wait seconds for the full response to get buffered.

How can I stream data out of stdout?

**Comment by smheidrich** [comment]
Wouldn't calling just ``(bzcat < 'test.bz2').popen()`` and streaming from the returned object's ``stdout`` work? From [the docs](https://plumbum.readthedocs.io/en/latest/local_commands.html#run-and-popen) (emphasis mine):
>And, if you want to want to execute commands “in the background” (i.e., not wait for them to finish), you can use the popen method, which returns a **normal subprocess.Popen object** [...] You can read from its stdout, wait() for it, terminate() it, etc.

So for me something like this seems to work:

``` python
from plumbum.cmd import cat

chain = (cat < "/some/huge/file.iso")
p = chain.popen()

CHUNKSIZE = 1024
chunk = None
with open("/tmp/output_file.iso", "wb") as of:
  while chunk != b"":
    chunk = p.stdout.read(CHUNKSIZE)
    of.write(chunk)
```

Or am I misunderstanding the question?

**Comment by brianbienvenu** [comment]
@smheidrich thank you very much! You're correct, that seems to work as I wanted.

I had previously gotten to this stage and gave up on `.popen()`:

    chain = (bzcat < fp).popen()
    print(dir(chain))
    ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', 
    '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', 
    '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', 
    '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_proc', '_start_time', 
    'argv', 'custom_encoding', 'iter_lines', 'verify']

There's no stdout in the `dir()` of the Popen object, but it exists:

    print(chain.stdout)
    <_io.BufferedReader name=7>

**Comment by smheidrich** [comment]
@brianbienvenu Yeah that is confusing; as far as I understand, it's because the "``Popen``-like" object is actually [``PlumbumLocalPopen``](https://github.com/tomerfiliba/plumbum/blob/bd2ff836c6cc3c8e4729f97f5f1d327568a71168/plumbum/machines/local.py#L36-L46) and it only gives access to ``subprocess.Popen`` methods via ``__getattr__``, so they're not visible in ``dir``.

I don't know, is there anything like [``functools.wraps``](https://docs.python.org/3/library/functools.html#functools.wraps) but for classes that one could use here to get the full information of the underlying object? Also no idea why it doesn't just derive from ``Popen``, but there's probably a good reason.
