### ISSUE TITLE
Python 2.7.15 - Chain fails TypeError: unsupported operand type(s) for |: 'unicode' and 'unicode'

### ISSUE THREAD

**Issue by bhyde** [tomerfiliba/plumbum#440]
I feel like I'm doing something foolish, but I don't know what.  

Python 2.7.15, plumbum==1.6.7, LC_ALL is en_US.UTF-8

```
>>> from plumbum.cmd import echo, tr
>>> echo("hi")
u'hi\n'
>>> (echo("hi")|tr("-d", "i"))()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'unicode' and 'unicode'
>>>
```

WDYT?

**Comment by henryiii** [comment]
The foolish thing you are doing is using Python 2. 😉  Oh, you mean the code! Round brackets evaluate and return a string. You need to use square brackets.

```python
(echo["hi"] | tr["-d", "i"])()
```

**Comment by bhyde** [comment]
Joy!  Thanks.  And, your right, i have 2 problems.   At least.
