### ISSUE TITLE
Chain SshMachine for use with a jump box.

### ISSUE THREAD

**Issue by freshwuzhere** [tomerfiliba/plumbum#460]
Apologies if this dealt with here or in the API docs but I can log into our jump box successfully and I have tried many ways to initiate a further ssh to the next server.  Can Plumbum handle this configuration?   Tried Paramiko and SshMachine without success.   Tried -A and -t parameters in one both and all invitations, etc.

Thanks for assistance

**Comment by zgaleaz** [comment]
If you construct the SshMachine with the right values for your ultimate destination, and also pass the constructor: ssh_opts=["-J", "xxx@jumpboxhost"], that should work
