### ISSUE TITLE
Background command blocks on stdout

### ISSUE THREAD

**Issue by Janzert** [tomerfiliba/plumbum#48]
A command set to run in the background (or with cmd.popen) will block after filling its stdout buffer until .wait() is called.

I'm not sure there is a way to fix this. Just adding a warning in the documentation might be the best that can be done.

**Comment by Vad1mo** [comment]
All the links are a dead. Some info or examples on how to monitor the bg thread and its output would be very helpful.

I need to start a process in the background and monitor its output for a specific string if it's not there, restart the process.

**Comment by henryiii** [comment]
I've fixed the 10-year-old links above by locking them to v1.0.0.
