### ISSUE TITLE
Docs Request: TypedEnv

### ISSUE THREAD

**Issue by AndydeCleyre** [tomerfiliba/plumbum#488]
I don't think the `TypedEnv` docstring sufficiently demonstrates the purpose, behavior, and usage examples of the feature. I'd add docs myself, but I don't know the answers yet.

It would probably be good to show an inconvenience when using `local.env` followed by the alternative made available via `TypedEnv`.

**Comment by AndydeCleyre** [comment]
@koreno 

Could you please add a little more documentation, or provide some examples in a comment here?

**Comment by koreno** [comment]
Yes, I'll try to get to it soon, thanks for the interest :)
