### ISSUE TITLE
Correct way to use less command with plumbum

### ISSUE THREAD

**Issue by kfaseela** [tomerfiliba/plumbum#510]
I am evaluating plumbum for one of my use cases to build a custom shell.
What I cannot get working is commands where a separate terminal is required. For eg : less or more. May I know if this is supported, I tried the command the below way, and it simply prints the output.

from plumbum import local
cat = local["cat"]
cmd = cat["file.txt"] | local["less"]
cmd()

I did see the terminal.py where a separate pager command is implemented, is that the only way to use "more and less" commands? It would have been easier if this is internally detected.
https://github.com/tomerfiliba/plumbum/blob/master/plumbum/cli/terminal.py#L195

**Comment by AndydeCleyre** [comment]
You'll want to run the command in the foreground. For example:

```python
from plumbum.cmd import cat, less
from plumbum import FG

cmd = (cat['file.txt'] | less)
cmd & FG
```

or

```python
from plumbum.cmd import cat, less

cmd = (cat['file.txt'] | less)
cmd.run_fg()
```

**Comment by kfaseela** [comment]
Thank you @AndydeCleyre , that saves a lot of time for me!
