### ISSUE TITLE
Issue with stdin and stdout redirect in single chain

### ISSUE THREAD

**Issue by kfaseela** [tomerfiliba/plumbum#511]
I am not able to get stdin and stdout redirects in single command chain work. Am I missing something in the usage?

I would like to execute command "/usr/bin/wc -l < input.txt > output.txt"

$ /opt/maglev/bin/python
Python 2.7.12 (default, Oct  8 2019, 14:14:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from plumbum import local
>>> wc = local["wc"]
>>> chain = wc["-l"] < "input.txt"
>>> print chain
/usr/bin/wc -l < input.txt
>>> chain()
u'4\n'
>>> chain = wc["-l"] < "input.txt" > "output.txt"
>>> print chain
False
>>> chain()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'bool' object is not callable
>>>

**Comment by AndydeCleyre** [comment]
You've just got to group those redirection bits that form new commands with parentheses:

```python
chain = (wc['-l'] < 'input.txt') > 'output.txt'
```

There's a note about this under [this example in the manual](https://plumbum.readthedocs.io/en/latest/local_commands.html#input-output-redirection).

**Comment by kfaseela** [comment]
Thanks for the information!

As I am directly using the command class, and invoking the respective overloaded operators for specific redirections(eg: __or__ method for "|" and so on), could you please let me know how exactly the parenthesis gets mapped here?
https://github.com/tomerfiliba/plumbum/blob/master/plumbum/commands/base.py#L52

**Comment by AndydeCleyre** [comment]
Sorry, I don't know what you're looking for, but if you post an example of code that's not working as you want or expect, I'll try to help iron it out.

**Comment by kfaseela** [comment]
I am trying to convert a bash like syntax command string to plumbum syntax:
=======================================================

SUPPORTED_REDIRECTION_MAP = {'|': 'or', '>': 'gt', '>>': 'rshift', '<': 'lt'}
FILE_REDIRECTION_OPERATORS = ['>>', '>', '<']
SUPPORTED_REDIRECTION_OPERATORS = ['|']+FILE_REDIRECTION_OPERATORS

def plumbum_command_builder(command_name, command_params=None):
    try:
        command = local[command_name]
    except CommandNotFound:
        return command_name
    return command[command_params]


def apply_redirection_operator(a, op, b):
    method = '__%s__' % shell_constants.SUPPORTED_REDIRECTION_MAP[op]
    return getattr(a, method)(b)

def plumbum_command_builder(command_name, command_params=None):
    try:
        command = local[command_name]
    except CommandNotFound:
        return command_name
    return command[command_params]

With these two util methods, I parse my input string and recursively convert it to plumbum syntax:
def build_plumbum_command(self, cmd):
// Omitting other code portions which split the cmd string at each redirection operator
      apply_redirection_operator(plumbum_command_builder(sub_command[0], sub_command[1:]), redirection_token, build_plumbum_command(pending_command))

As you can see, apply_redirection_operator is applying the overload operator methods of LocalCommand classes from plumbum and finally constructing a chained bound command.

For eg : 

If I run this for a string ""wc -l < input.txt"" ==> it works without any issues.
But if I use the same for "wc -l < input.txt > output.txt" ==> throws error:

Traceback (most recent call last):
  File "redirection-filepath.1.py", line 82, in <module>
    print(chain())
  File "/opt/maglev/local/lib/python2.7/site-packages/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/opt/maglev/local/lib/python2.7/site-packages/plumbum/commands/base.py", line 231, in run
    with self.bgrun(args, **kwargs) as p:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/maglev/local/lib/python2.7/site-packages/plumbum/commands/base.py", line 185, in bgrun
    p = self.popen(args, **kwargs)
  File "/opt/maglev/local/lib/python2.7/site-packages/plumbum/commands/base.py", line 451, in popen
    return self.cmd.popen(args, **kwargs)
  File "/opt/maglev/local/lib/python2.7/site-packages/plumbum/commands/base.py", line 312, in popen
    return self.cmd.popen(self.args + list(args), **kwargs)
  File "/opt/maglev/local/lib/python2.7/site-packages/plumbum/machines/local.py", line 131, in popen
    **kwargs)
  File "/opt/maglev/local/lib/python2.7/site-packages/plumbum/machines/local.py", line 312, in _popen
    **kwargs)  # bufsize = 4096
  File "/opt/maglev/local/lib/python2.7/site-packages/plumbum/machines/local.py", line 40, in __init__
    self._proc = Popen(*args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 703, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "/usr/lib/python2.7/subprocess.py", line 1126, in _get_handles
    p2cread = stdin.fileno()
AttributeError: 'StdoutRedirection' object has no attribute 'fileno'

**Comment by AndydeCleyre** [comment]
You can preserve the formatting better in these comments using the [github flavored markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

If you have code parsing and splitting on the redirection operators, that will have to group each use of an operator into a command.

But it may be worth asking why all this is worth doing at all. You can also use plumbum to call `bash -c` on any bash string. What's the ultimate goal?

**Comment by kfaseela** [comment]
@AndydeCleyre : I am designing a custom shell, and hence cannot call bash -c

**Comment by AndydeCleyre** [comment]
Probably a better tool for your task is [prompt toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit), though you may want to check out whatever is being done by xonsh, Mario, and daudin.

**Comment by kfaseela** [comment]
I am yet to look into prompt toolkit, as this is already progressed so much with plumbum. I was able to get the command chaining working by fixing the parsing logic to expand commands as and when a new redirection operator is met.

One other question is, Ian using run_fg() to get terminal commands working. But I do have external scripts who try to login to my shell via paramiko, and for them they are not getting any response in stdout and it times out

stdin, stdout, stderr = ssh.exec_command('magctl appstack status',timeout=20)
