### ISSUE TITLE
CI updates

### ISSUE THREAD

**Issue by henryiii** [tomerfiliba/plumbum#531]
This is a followup to #526 , listing some things that still need to be done:

- [x] Set up pre-commit to take over running flake8
- [x] deploy
- [x] check readthedocs
- Check conda recipe

**Comment by henryiii** [comment]
@tomerfiliba We need to prepare for a 1.7.0 release in the near future. After dropping travis due to them dropping OS support, we now need a `__token__` (which is more secure anyway) for GitHub Actions. Can you go to PyPI, Account Settings, Add API token,  and set the scope: Plumbum, then to Github (this repo) Settings -> Secrets and add the token with the name `pypi_password`? If you need some links, https://github.com/marketplace/actions/pypi-publish describes or links to descriptions of some of it.

I do have rights to make the token on PyPI, but I don't have access to the Settings tab on this repo, so it doesn't do me much good.

Also, if you could turn on "build PRs" in the main settings page of ReadTheDocs, that would be useful too. :)

**Comment by tomerfiliba** [comment]
i think i did it right.

also, it seems that build PRs is already set on rtfd:

[image: image.png]

-----------------------------------------------------------------

*Tomer Filiba*
tomerfiliba.com

**Comment by henryiii** [comment]
Excellent, thank you! I'll release this weekend, then - if it fails, I'll ping you and publish manually this time.

**Comment by henryiii** [comment]
Worked beautifully (once I remembered to trigger on releases, anyway). Thanks! 1.7.0 is out.
