### ISSUE TITLE
ImportError: cannot import name 'git' from 'plumbum.cmd'

### ISSUE THREAD

**Issue by zxm14** [tomerfiliba/plumbum#639]
Hi, I'm new to plumbum and GitHub. When I initialized a [copier](https://copier.readthedocs.io/en/stable/) folder, it turned out to be this

> from plumbum.cmd import git
ImportError: cannot import name 'git' from 'plumbum.cmd' (D:\Program Files\Python310\lib\site-packages\plumbum\cmd.py)

Is it really able to import git from plumbum.cmd? What can i do to solve these problem?

**Comment by sisp** [comment]
Is Git installed on your machine?

**Comment by henryiii** [comment]
I don't think we can improve the error message with the import shortcut. If you can't import X from `plumbum.cmd` that means `X` is not installed on your machine.
