### ISSUE TITLE
1.8.2: plumbum doesnt support symbol Tilde

### ISSUE THREAD

**Issue by Laplacence** [tomerfiliba/plumbum#657]
When I use the tilde, plumbum prompts an error

```
>>> local.cwd.chdir('~/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/plumbum/path/local.py", line 332, in chdir
    os.chdir(str(newdir))
FileNotFoundError: [Errno 2] No such file or directory: '~/'
```

**Comment by henryiii** [comment]
There's also `os.path.expanduser`, which is much better than a system call. If we did it by default then you'd not be able to access files that actually have `~` in them.  Same thing with `os.path.expandvars`.

**Comment by Laplacence** [comment]
Many thanks to @youk  and @henryiii for their replies, I'll look into the source code more closely.
