### ISSUE TITLE
Invoking CLI programmatically with parent command switches

### ISSUE THREAD

**Issue by jake-miles** [tomerfiliba/plumbum#689]
Hello. I love plumbum. I'm writing tests around a CLI with subcommands. Is it possible to provide parent switches to a subcommand when using `invoke`?
```
class MyCli(cli.Application):

    flag = cli.Flag("--flag")

    def main(self):
        pass

@MyCli.subcommand('sub')
class Sub(cli.Application):
    def main(self, *args):
        print(args)    

Sub.invoke("arg1", "arg2", flag=True)
```
The alternative, I believe, is to call `run` instead, providing the switches as part of the `argv` list of string arguments. Is this intentionally not supported with `invoke`? Is there something I'm missing in how to do this?

**Comment by piotr-dobrogost** [comment]
How did you solve this?

**Comment by jake-miles** [comment]
@piotr-dobrogost I worked around it as described above - call `run` instead with all the args as an array of strings, providing `exit=False` so it doesn't call `sys.exit`, and then test using the retcode, stdout, stderr, and mocking any effects.
